name: Kwadwo
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: "Kwadwo's Grid"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.25
  lightness: 0.2982995
  saturation: 0.778393
  rhythmicContrast: 0.03891537
purpose: []
